typst-compose side-by-side 1 gray --root ../../..
typst-compose side-by-side-kwargs 1 gray --root ../../..
typst-compose big 1 gray --root ../../..
typst-compose big-complex 3 gray --root ../../..
typst-compose progress 3 gray --root ../../..
typst-compose sections-band 2 gray --root ../../..
typst-compose sections 4 gray --root ../../..
typst-compose full-width 1 gray --root ../../..
typst-compose next-heading 3 gray --root ../../..
