simple:
	pdftoppm ../examples/simple.pdf ./simple -png
	montage ./simple-* -geometry +50+50 -background LightGray ./simple.png
	rm ./simple-*

university:
	pdftoppm ../examples/university.pdf ./university -png
	montage ./university-* -geometry +50+50 -background LightGray ./university.png
	rm ./university-*
