[book]
authors = ["Andreas Kröpelin"]
language = "en"
multilingual = false
src = "src"
theme = "theme"
title = "Polylux"

[output.html]
site-url = "/polylux/book/"

[output.html.code.hidelines]
typ = "~"

[preprocessor.typst-highlight]
#disable_inline = true
#highlight_without_lang = true